[package]
name = "tcp-srvc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
log = "0.4.17"
log4rs = "1.1.1"
tokio = {version = "1",features = ["full"]}
